export const REGISTRO_INIT      = "REGISTRO_INIT"
export const REGISTRO_SUCCESS   = "REGISTRO_SUCCESS"
export const REGISTRO_ERROR     = "REGISTRO_ERROR"
export const BUSQUEDA_SIN_REGISTRO = "BUSQUEDA_SIN_REGISTRO"
export const LOGOUT = 'LOGOUT'