export const REGISTRO_INIT      = "REGISTRO_INIT"
export const REGISTRO_SUCCESS   = "REGISTRO_SUCCESS"
export const REGISTRO_ERROR     = "REGISTRO_ERROR"
export const BUSQUEDA_SIN_REGISTRO = "BUSQUEDA_SIN_REGISTRO"
export const LOGOUT = 'LOGOUT'

export const SET_PRESENTACION_FILTRO    = 'SET_PRESENTACION_FILTRO'
export const SET_ESTADO_FILTRO          = 'SET_ESTADO_FILTRO'
export const SET_LINEA_FILTRO           ="SET_LINEA_FILTRO"

export const BORRAR_PRESENTACION_FILTRO    = 'BORRAR_PRESENTACION_FILTRO'
export const BORRAR_ESTADO_FILTRO          = 'BORRAR_ESTADO_FILTRO'
export const BORRAR_LINEA_FILTRO           = 'BORRAR_LINEA_FILTRO'

export const SET_PRODUCTO = "SET_PRODUCTO"
export const OBTENER_PRODUCTO_INIT      = "OBTENER_PRODUCTO_INIT"
export const OBTENER_PRODUCTO_SUCCESS   = "OBTENER_PRODUCTO_SUCCESS"
export const OBTENER_PRODUCTO_ERROR     = "OBTENER_PRODUCTO_ERROR"